### ISSUE TITLE
Prism Plugin: error in BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts

### ISSUE THREAD

**Issue by Perlover** [Kukks/BTCPayServerPlugins#12]
Hello,

Some mistakes are constantly falling down. The server is slow. I'm not sure if it's because of your plugin, but there are also frequent errors

`docker logs -f e01705d3859b` (docker image as `btcpayserver/btcpayserver:1.9.1`)

```
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
fail: BTCPayServer.Plugins.Prism.SatBreaker: Error while checking payouts
System.NullReferenceException: Object reference not set to an instance of an object.
   at BTCPayServer.Plugins.Prism.SatBreaker.CheckPayouts(CancellationToken cancellationToken) in /build/Plugins/BTCPayServer.Plugins.Prism/SatBreaker.cs:line 142
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
info: BTCPayServer.Plugins.LNbank.Services.LightningInvoiceWatcher: Processing 1 transactions
```

**Comment by Kukks** [comment]
I believe I may have fixed this in latest version. Reopen if still the case.
