### ISSUE TITLE
 [Bug]: prism: payouts always stuck

### ISSUE THREAD

**Issue by massmux** [Kukks/BTCPayServerPlugins#28]
btcpay 1.12
prism  1.2.2.0

tested with these sources: lnbits, alby, localnode
payouts are always stuck. in the previous version all was ok (a part with lnbits which did not work even before)

to replicate 
just activate a prism to a destination. when a payment arrives that should trigger the payout. it always remain pending awaiting

**Comment by Kukks** [comment]
Any logs?

**Comment by massmux** [comment]
info: PayServer:      BTC (Lightning): Payment detected via notification (T4cJWZAsbhQmUg26WBUsE)
info: PayServer:      BTC (Lightning): No more invoice to listen on https://admin:xxx/lndhub/ext/, releasing the connection.
System.FormatException: Invalid string
   at NBitcoin.Network.Parse(String str, Type targetType)
   at NBXplorer.DerivationStrategy.DerivationStrategyFactory.ParseCore(String str)
   at BTCPayServer.DerivationSchemeParser.Parse(String str) in /source/BTCPayServer/DerivationSchemeParser.cs:line 196
   at BTCPayServer.Plugins.Prism.OnChainPrismClaimCreate.Execute(Object args) in /build/Plugins/BTCPayServer.Plugins.Prism/OnChainPrismClaimCreate.cs:line 44
fail: BTCPayServer.Plugins.PluginHookService: Filter on hook prism-claim-create failed
System.FormatException: Invalid string
   at NBitcoin.Network.Parse(String str, Type targetType)
   at NBXplorer.DerivationStrategy.DerivationStrategyFactory.ParseCore(String str)
   at BTCPayServer.DerivationSchemeParser.Parse(String str) in /source/BTCPayServer/DerivationSchemeParser.cs:line 196
   at BTCPayServer.Plugins.Prism.OnChainPrismClaimCreate.Execute(Object args) in /build/Plugins/BTCPayServer.Plugins.Prism/OnChainPrismClaimCreate.cs:line 44
   at BTCPayServer.Plugins.PluginHookService.ApplyFilter(String hook, Object args) in /source/BTCPayServer/Plugins/PluginHookService.cs:line 53
info: LightningAutomatedPayoutSenderFactory:8FvFXPQTN1dUMbvor7jezdRkZo1a4NvhZtQfmvM5v9qW:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:05:00)
info: LightningAutomatedPayoutSenderFactory:8FvFXPQTN1dUMbvor7jezdRkZo1a4NvhZtQfmvM5v9qW:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:05:00)
info: LightningAutomatedPayoutSenderFactory:8FvFXPQTN1dUMbvor7jezdRkZo1a4NvhZtQfmvM5v9qW:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:05:00)
info: LightningAutomatedPayoutSenderFactory:8FvFXPQTN1dUMbvor7jezdRkZo1a4NvhZtQfmvM5v9qW:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:05:00)
info: LightningAutomatedPayoutSenderFactory:8FvFXPQTN1dUMbvor7jezdRkZo1a4NvhZtQfmvM5v9qW:BTC_LightningLike: 1 found to process. Starting (and after will sleep for 00:05:00)

**Comment by massmux** [comment]
moreover the change of source for lightning seems not working. for example if i have a source to a LNDHUB location and i want to change to lnbank, i got a blank page and the change is not executed.

`
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN01DQF1688H", Request id "0HN01DQF1688H:00000001": An unhandled exception was thrown by the application.
System.FormatException: The format of the connectionString should a list of key=value delimited by semicolon
   at BTCPayServer.Lightning.LightningConnectionStringHelper.ExtractValues(String connectionString, String& type)
   at BTCPayServer.Extensions.IsSafe(ILightningClient connectionString) in /source/BTCPayServer/Extensions.cs:line 107
   at BTCPayServer.Controllers.UIStoresController.SetupLightningNode(String storeId, LightningNodeViewModel vm, String command, String cryptoCode) in /source/BTCPayServer/Controllers/UIStoresController.LightningLike.cs:line 154
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)

`

**Comment by massmux** [comment]
situation update:

info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.12.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Prism - 1.2.3.0

unfortunately prism still does not work.  i see no errors in log. the payouts remain always awaiting.

**Comment by Kukks** [comment]
> situation update:
> 
> info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.12.2 info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Prism - 1.2.3.0
> 
> unfortunately prism still does not work. i see no errors in log. the payouts remain always awaiting.

Should be fixed with 1.2.4
