### ISSUE TITLE
Coinjoin plugin crashes the whole BTCPayserver

### ISSUE THREAD

**Issue by gus4rs** [Kukks/BTCPayServerPlugins#59]
Plugin was working fine, against BTCPayserver v1.13.5. Upon restart, the whole server throws errors and is not accessible anymore. 

Full log:

```
info: Configuration:  Data Directory: /root/.btcpayserver/Main
info: Configuration:  Configuration File: /root/.btcpayserver/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Bitcoin - 1.13.5.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Wabisabi - 1.0.92.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://127.0.0.1:24444/
info: Configuration:  BTC: Cookie file is /home/user/.nbxplorer/Main/.cookie
info: Configuration:  Network: Mainnet
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: PayServer:      Checking if any payment arrived on lightning while the server was offline...
info: PayServer:      Processing lightning payments...
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
info: PayServer:      0 pending payment requests being checked since last run
info: BTCPayServer.Plugins.Wabisabi.WabisabiPlugin: 2024-09-02 14:33:21.976 [9] INFO	CoinJoinIdStore.Create (79)	0 coinjoins were imported from files.
      
info: BTCPayServer.Plugins.Wabisabi.WabisabiPlugin: 2024-09-02 14:33:22.107 [5] INFO	HostedServices.StartAllAsync (61)	Started RoundStateUpdater.
      
info: BTCPayServer.Plugins.Wabisabi.WabisabiPlugin: 2024-09-02 14:33:22.113 [9] INFO	HostedServices.StartAllAsync (61)	Started WasabiCoordinatorStatusFetcher.
      
info: BTCPayServer.Plugins.Wabisabi.WabisabiPlugin: 2024-09-02 14:33:22.115 [17] INFO	HostedServices.StartAllAsync (61)	Started WasabiCoordinatorStatusFetcher.
      
info: Configuration:  Now listening on: http://0.0.0.0:23000
info: f01ad927b14c4b65d305ccb2bc58f1b8cc5b1f69e08ef38ea8e117b578faafec: Connected to coordinator
fail: BTCPayServer.Plugins.Wabisabi.WalletProvider: REPORT THIS CRASH! Derivnull? False, coinpath?True 
System.NullReferenceException: Object reference not set to an instance of an object.
   at NBitcoin.ExtPubKey.Derive(KeyPath derivation)
   at NBXplorer.DerivationStrategy.DirectDerivationStrategy.GetChild(KeyPath keyPath)
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_2.<<LoadCoins>b__7>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 196
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
info: PayServer:      User a@b.com logged out
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Could not compute coin candidate: Object reference not set to an instance of an object.
fail: BTCPayWallet_T1mgGrNQjSDMLtum3mdNNHSTxDD2sKyP9vjpb28a7gV: Coinjoin aborted with error: NoCoinsEligibleToMix. No candidate coins available to mix.
info: PayServer:      User a@b.com logged in
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at NBitcoin.ExtPubKey.Derive(KeyPath derivation)
   at NBXplorer.DerivationStrategy.DirectDerivationStrategy.GetChild(KeyPath keyPath)
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_2.<<LoadCoins>b__7>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 196
--- End of stack trace from previous location ---
   at BTCPayServer.Plugins.Wabisabi.Smartifier.LoadCoins(List`1 coins, Int32 current, Dictionary`2 utxoLabels) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 190
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_1.<<LoadCoins>b__2>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 172
--- End of stack trace from previous location ---
   at BTCPayServer.Plugins.Wabisabi.Smartifier.LoadCoins(List`1 coins, Int32 current, Dictionary`2 utxoLabels) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 142
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_1.<<LoadCoins>b__2>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 172
--- End of stack trace from previous location ---
   at BTCPayServer.Plugins.Wabisabi.Smartifier.LoadCoins(List`1 coins, Int32 current, Dictionary`2 utxoLabels) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 142
   at BTCPayServer.Plugins.Wabisabi.BTCPayWallet.GetAllCoins() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/BTCPayWallet.cs:line 204
   at AspNetCoreGeneratedDocument.Views_Shared_Wabisabi_WabisabiDashboard.ExecuteAsync() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Views/Shared/Wabisabi/WabisabiDashboard.cshtml:line 68
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at AspNetCoreGeneratedDocument.Components_UiExtensionPoint_Default.ExecuteAsync() in /home/user/btcpayserver/BTCPayServer/Components/UiExtensionPoint/Default.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_UIStores_Dashboard.__Generated__UiExtensionPointViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_UIStores_Dashboard.ExecuteAsync() in /home/user/btcpayserver/BTCPayServer/Views/UIStores/Dashboard.cshtml:line 56
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HN6BAH8MCF8B", Request id "0HN6BAH8MCF8B:00000007": An unhandled exception was thrown by the application.
System.InvalidOperationException: The exception handler configured on ExceptionHandlerOptions produced a 404 status response. This InvalidOperationException containing the original exception was thrown since this is often due to a misconfigured ExceptionHandlingPath. If the exception handler is expected to return 404 status responses then set AllowStatusCode404Response to true.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NBitcoin.ExtPubKey.Derive(KeyPath derivation)
   at NBXplorer.DerivationStrategy.DirectDerivationStrategy.GetChild(KeyPath keyPath)
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_2.<<LoadCoins>b__7>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 196
--- End of stack trace from previous location ---
   at BTCPayServer.Plugins.Wabisabi.Smartifier.LoadCoins(List`1 coins, Int32 current, Dictionary`2 utxoLabels) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 190
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_1.<<LoadCoins>b__2>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 172
--- End of stack trace from previous location ---
   at BTCPayServer.Plugins.Wabisabi.Smartifier.LoadCoins(List`1 coins, Int32 current, Dictionary`2 utxoLabels) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 142
   at BTCPayServer.Plugins.Wabisabi.Smartifier.<>c__DisplayClass19_1.<<LoadCoins>b__2>d.MoveNext() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 172
--- End of stack trace from previous location ---
   at BTCPayServer.Plugins.Wabisabi.Smartifier.LoadCoins(List`1 coins, Int32 current, Dictionary`2 utxoLabels) in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Smartifier.cs:line 142
   at BTCPayServer.Plugins.Wabisabi.BTCPayWallet.GetAllCoins() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/BTCPayWallet.cs:line 204
   at AspNetCoreGeneratedDocument.Views_Shared_Wabisabi_WabisabiDashboard.ExecuteAsync() in /build/Plugins/BTCPayServer.Plugins.Wabisabi/Views/Shared/Wabisabi/WabisabiDashboard.cshtml:line 68
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at AspNetCoreGeneratedDocument.Components_UiExtensionPoint_Default.ExecuteAsync() in /home/user/btcpayserver/BTCPayServer/Components/UiExtensionPoint/Default.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.ViewViewComponentResult.ExecuteAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_UIStores_Dashboard.__Generated__UiExtensionPointViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_UIStores_Dashboard.ExecuteAsync() in /home/user/btcpayserver/BTCPayServer/Views/UIStores/Dashboard.cshtml:line 56
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 97
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 30
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /home/user/btcpayserver/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 29
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by gus4rs** [comment]
Further info: the crash happens when accessing the Dashboard

**Comment by Kukks** [comment]
should be fixed now

**Comment by gus4rs** [comment]
How can I test it?
